name: Prettier Formatter
on: [push]

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Run Prettier
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --check "**/*.{js,jsx,ts,tsx,json,css,md}"
