name: Publish to npm
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          registry-url: 'https://registry.npmjs.org'
      # trusted publishing needs npm 11 which is not the default yet
      - name: Update npm
        run: npm install -g npm@latest
      - uses: pnpm/action-setup@v2
        with:
          version: 10
      - name: Install dependencies
        run: "cd src && pnpm install"
      - run: "cd src && pnpm publish --provenance --access public --no-git-checks"

